version: '2'

services:
  ldap_server:
    image: erlangms/ldap_server:2.0.7
    container_name: ldap_server
    ports:
    - 2389:2389
    shm_size: 2G
    stdin_open: true
    tty: true
    build: .
    volumes:
    - ./config/:/var/opt/erlangms/.erlangms/

