version: '2'

services:
  rest_server:
    image: erlangms/erlangms_rest_server
    ports:
    - 2301:2301
    hostname: erlangms
    shm_size: 4G
    stdin_open: true
    tty: true
    build: .
    #volumes:
    #- ./odbc.ini:/var/opt/erlangms/.odbc.ini
    #- ./config/:/var/opt/erlangms/.erlangms/
    #- ./deployments/:/var/opt/wildfly/standalone/deployments

