version: '2'

services:
  rest_server:
    image: erlangms/rest_server
    ports:
    - 2301:2301
    hostname: erlangms
    shm_size: 4G
    stdin_open: true
    tty: true
    build: .
    volumes:
    - ./config/:/var/opt/erlangms/.erlangms/
    - ./deployments/:/var/opt/wildfly/standalone/deployments

