version: '2'

services:
  frontend:
    image: erlangms/erlangms
    ports:
     - 80:2301
     - 8080:2301
    shm_size: 3G
    stdin_open: true
    tty: true
    build: .
    volumes:
     - ./config/:/var/opt/erlangms/.erlangms/
     - ./odbc.ini:/var/opt/erlangms/.odbc.ini
     - ./projects:/var/www/
    dns: 164.41.101.4 
    dns_search: 
     - ad-fub.unb.br

    

