version: '2'

services:
  frontend:
    image: erlangms/frontend
    ports:
     - 8081:2301
    shm_size: 450M
    stdin_open: true
    tty: true
    build: .
    volumes:
    - ./config/:/var/opt/erlangms/.erlangms/
    - ./projects:/var/www/
     

    

