version: '2'

services:
  frontend:
    image: erlangms/frontend
    ports:
     - 8081:2301
    shm_size: 250M
    stdin_open: true
    tty: true
    build: .
    volumes:
     - ./projects:/var/www/

    

