{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "erlangms-ldap",
    "namespace": "ssi",
    "selfLink": "/apis/extensions/v1beta1/namespaces/ssi/deployments/erlangms-ldap",
    "uid": "b0fa5a00-b032-11e8-8700-0050568169c4",
    "generation": 4,
    "creationTimestamp": "2018-09-04T11:07:19Z",
    "labels": {
      "name": "erlangms-ldap"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "4"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "name": "erlangms-ldap"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "name": "erlangms-ldap"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "erlangms-ldap-vol-config",
            "configMap": {
              "name": "erlangms-ldap-configs",
              "defaultMode": 420
            }
          }
        ],
        "containers": [
          {
            "name": "erlangms-ldap",
            "image": "dkr.unb.br/erlangms-ldap:latest",
            "ports": [
              {
                "containerPort": 389,
                "protocol": "TCP"
              },
              {
                "containerPort": 2389,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "erlangms-ldap-vol-config",
                "mountPath": "/var/opt/erlangms/.erlangms/"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always",
            "stdin": true,
            "tty": true
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 4,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-09-04T11:07:20Z",
        "lastTransitionTime": "2018-09-04T11:07:20Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      },
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2018-09-04T11:29:41Z",
        "lastTransitionTime": "2018-09-04T11:29:35Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"erlangms-ldap-59c7f776b7\" has successfully progressed."
      }
    ]
  }
}
