version: '2'

services:
  http_server:
    image: erlangms/http_server:2.0.4
    image: erlangms/http_server:latest
    ports:
    - 2301:2301
    shm_size: 3G
    stdin_open: true
    tty: true
    build: .
    volumes:
    - ./config/:/var/opt/erlangms/.erlangms/

