version: '2'

services:
  datacenter:
    image: dkr.unb.br/erlangms-datacenter:1.0.0
    image: dkr.unb.br/erlangms-datacenter:latest
    ports:
     - 8081:2301
    shm_size: 2G
    stdin_open: true
    tty: true
    build: .
    volumes:
    - ./config/:/var/opt/erlangms/.erlangms/
    - ./scripts:/var/scripts
    

     

    

