version: '2'

services:
  datacenter:
    image: erlangms/datacenter
    ports:
     - 8081:2301
    shm_size: 450M
    stdin_open: true
    tty: true
    build: .
    volumes:
    - ./config/:/var/opt/erlangms/.erlangms/
    - ./portal:/var/www/portal
     

    

